### ISSUE TITLE
Cannot run laser tracker, error when run

### ISSUE THREAD

**Issue by rogue92** [bradmontgomery/python-laser-tracker#1]
Hello,

I am attempting to run the laser tracker software on my Raspberry Pi for a school project.  I have put your code in directly to Python on the Pi (I have Python 2.7.3 on the device) and continually get the following error every time I run it.  What would be causing this? (by the way, thanks for coming up with this software...it is really cool from what I've read on your page and here on GitHub!)

Traceback (most recent call last):
File "home/pi/laser_tracker.py", line 252, in <module> : tracker.run()
File "home/pi/laser_tracker.py", line 167, in run: self.create_and_position_window('LaserPointer',0,0)
File "home/pi/laser_tracker.py", line 55, in create_and_position_window: cv2.resizeWindow(name, self.cam_width, self.cam_height)

AttributeError: 'module' object has no attribute 'resizeWindow'

**Comment by bradmontgomery** [comment]
This might be due to a newer version of OpenCV. Can you tell me what version you're using?

I haven't touched this code in quite a while, but I vaguely remember that a newer version of OpenCV had changed some of their GUI function calls.

**Comment by yemikudaisi** [comment]
2.3.1

**Comment by valeriyvan** [comment]
@rogue92, just comment out lines 82-90 in laser_tracker.py to solve this issue and don't set camera resolution, rely on defaults.
