### ISSUE TITLE
Clean up the code using pylint

### ISSUE THREAD

**Issue by ao2** [bradmontgomery/python-laser-tracker#11]
Hi, may I suggest to clean up the code using pylint?
I find it a little easier to contribute when the code meets the pyhton coding standards.

Thanks,
   Antonio

**Comment by bradmontgomery** [comment]
I typically run my python code through `flake8`, though this repo does not contain code I use on a daily basis. If you want to run the code through pylint and send me a PR I'd happily merge it. 

Thanks!
