### ISSUE TITLE
Do I connect a usb webcam to my computer?

### ISSUE THREAD

**Issue by Ankur** [bradmontgomery/python-laser-tracker#2]
Do I connect a webcam to my computer?  Then a white sheet of paper would be positioned in front of that cam, and the laser would be on that sheet, while the result would be displayed on the screen.  Correct?

**Comment by bradmontgomery** [comment]
Yes, that's the general idea. Pointing your camera at a relatively light-colored wall would work, too. You may have to play with the values for the hue and saturation to get it work optimally, though.
