### ISSUE TITLE
Python version and bitness

### ISSUE THREAD

**Issue by Ankur** [bradmontgomery/python-laser-tracker#3]
Would like to know what python version and bitness this was built with, so I don't run into any errors, thanks.

**Comment by bradmontgomery** [comment]
Python 2.x (it may have originally been built on 2.5, but should run on 2.6 or 2.7). This code should run on either 32-bit or 64-bit systems, but that will depend _heavily_ on how your OpenCV was compiled. If you compile OpenCV yourself or install from a package, that shouldn't be an issue. 

Note also from [the README](https://github.com/bradmontgomery/python-laser-tracker/blob/master/README.rst#requirments), that this code was last tested with OpenCV 2.4.5. It looks like there's a version 3.0 available now, so it's likely this code won't work with the latest OpenCV.
