### ISSUE TITLE
Using BGR instead of HSV

### ISSUE THREAD

**Issue by Ankur** [bradmontgomery/python-laser-tracker#4]
Would this be feasible?  And if so, how would it be done?

**Comment by bradmontgomery** [comment]
I think it would be possible, and I may have tried this (this code is pretty old, so I don't remember). The relevant place to look would be [where you split the image into it's channels](https://github.com/bradmontgomery/python-laser-tracker/blob/master/laser_tracker/laser_tracker.py#L120).  You'd have to look up the docs for opencv to see how to do that. Then in the [threshold_image](https://github.com/bradmontgomery/python-laser-tracker/blob/master/laser_tracker/laser_tracker.py#L96) function; you're probably need to re-write (or write a different function) do do that.

Cameras are better today than they were years ago, but you may have some issues with BGR thresholds being different on different cameras.

Let me know if you have any success with this.

**Comment by Ankur** [comment]
Ah yes, I've done some research and it looks like almost always, HSV is used.

By the way, I've got HSV working, thanks!

**Comment by bradmontgomery** [comment]
Excellent!  Happy it's working for you :smile:
