### ISSUE TITLE
bitwise_and and Otsu thresholding

### ISSUE THREAD

**Issue by ghost** [bradmontgomery/python-laser-tracker#5]
Hi!

I gave your code a try and [modified it a bit](https://github.com/bradmontgomery/python-laser-tracker/compare/master...vross:master) (should I send a pull request?). However, I have a few questions:
- I am a bit confused about the usage of the <code>bitwise_and</code> operation on the hue, saturation and value. If I understood correctly, these values are encoded on 8 bits, so we might have problems because:
  
  <pre><code>>>> import cv2 
  >>> import numpy
  >>> b = numpy.array([[0, 5], 
                       [4, 3]])
  >>> c = numpy.array([[0, 1], 
                       [2, 3]])
  >>> cv2.bitwise_and(b, c)
  array([[0, 1], 
         [0, 3]], dtype=int32)
  #4 (0b100) and 2 (0b010) gives 0
  </code></pre>
  
  Did I miss something?
- You chose to use the [Otsu](http://www.labbookpages.co.uk/software/imgProc/otsuThreshold.html) algorithm. The result is quite strange for me. I guess the reason is that the threshold is computed by the algorithm and is not the one that is given by the user. Could you explain this choice (I am no expert in image processing)? :)

And thank you for this code!

**Comment by bradmontgomery** [comment]
Hi @vross, Yes, please send a pull request! If your changes improve this, I'd love to merge them back in.

I'll try to answer your questions, but honestly, I'm no expert with this kind of thing either! Most of my original decisions were based on experimentation when I originally wrote this code (~2006-ish).
- regarding `bitwise_and`: My goal was to amplify the signal from the laser. I made the assumption that it would be the brightest pixels in the screen and I was not sure if I could use a single channel (e.g. value) or if I could simplify the task by throwing away some data (e.g. like I did with saturation). Using a `bitwise_and` was my attempt at simplifying that data. It seemed to work at the time, so I went with it, but as you mentioned, this may not work.
- regarding OTSU: I have no idea why I picked this. I probably read that from an OpenCV example somewhere, and just left it in!

Thanks for contributing!

**Comment by ghost** [comment]
There was indeed a problem with thresolding. The pull request has been done. :)
